Redownload CRDB if previous download got killed in the middle
cockroachdb/cockroach-go pull request #112
Opened 2021-08-25 20:51 UTC by ZhouXing19

Resolve #102

This commit is to add a flock to the local file when downloading CRDB binary.
If one process finds the localfile for CRDB binary already exists, but in unfinished 
mode and can be flocked, it means  the previous download process was killed 
before it finished. In this case, this process removes the existing local file 
and redownload CRDB binary.

Tests are added in `TestFlockOnDownloadedCRDB()` at `testserver_test.go`. 
Note that test does not fully simulate the `downloading gets killed halfway` scenario.
A recording with two downloading processes in CLI is [here](https://www.dropbox.com/s/awxvc70wfg4h0yc/testserver-redownloading.mp4?dl=0)

2021-09-09 22:24 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[testserver/binaries.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBaP3N7u_qh2BItVdu:-MjBaP3O2BVCrsVs5EUT:b-te83gi) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L56)):*
> ```Go
> 	if _, err := localFileLock.TryLock(); err != nil {
> 		return err
> 	}
> ```

i think it would be safest to add
```
defer func() { _ = localFileLock.Unlock() }()
```
___
*[testserver/binaries.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBajpaE4tTOfnXoczd:-MjBajpaE4tTOfnXocze:b-6fgi6f) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L73)):*
> ```Go
> 	}
> 
> 	if err := localFileLock.Close(); err != nil {
> ```

nit: i think `localFileLock.Unlock()` would be a bit more readable
___
*[testserver/binaries.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBapiN3is_bLOmZjVY:-MjBapiN3is_bLOmZjVZ:bk6f028) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L84)):*
> ```Go
> var muslRE = regexp.MustCompile(`(?i)\bmusl\b`)
> 
> func GetDownloadResponse() (*http.Response, error) {
> ```

nit: add a comment to the function now that it's public
___
*[testserver/binaries.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBbH8F4mvyN5aQnVuB:-MjBbH8F4mvyN5aQnVuC:bzdsklz) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L164)):*
> ```Go
> 		localFileLock := flock.New(localFile)
> 		// If there's a process downloading the binary, local file cannot be flocked.
> 		canBeLocked, err := localFileLock.TryLock()
> ```

nit: instead of `canBeLocked`, the name `locked` is more understandable
___
*[testserver/binaries.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBbftK6eIENP-qTpIT:-MjBbftK6eIENP-qTpIU:b-58wpi5) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L165)):*
> ```Go
> 		// If there's a process downloading the binary, local file cannot be flocked.
> 		canBeLocked, err := localFileLock.TryLock()
> 		if err == nil {
> ```

nit: the error handling is more readable like this:

```
if err != nil {
  return "", err
}
if locked {
  // If local file can be locked ...
  // ... rest of the code
}
```

___
*[testserver/binaries.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBc17G0XCriq-PThbQ:-MjBc17G0XCriq-PThbR:b2yhayb) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L169)):*
> ```Go
> 				// If local file can be locked, it means the previous download was
> 				// killed half way. Delete local file and re-download.
> 				log.Printf("Find half-way failed download, delete and re-download")
> ```

nit: change to "previous download failed in the middle, deleting and re-downloading"
___
*[testserver/binaries.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBcF3b8QqDtC6SvNu2:-MjBcF3b8QqDtC6SvNu3:b-35nzkl) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L171)):*
> ```Go
> 				log.Printf("Find half-way failed download, delete and re-download")
> 				if err := os.Remove(localFile); err != nil {
> 					log.Printf("failed to remove half-way failed download %s: %s", localFile, err)
> ```

nit: change to "failed to remove partial download %s: %v"
___
*[testserver/binaries.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBdFpA3xRbZVynnHOw:-MjBdFpA3xRbZVynnHOx:b3zi7v9) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L186)):*
> ```Go
> 	err = downloadFile(response, localFile, tc)
> 	if err != nil {
> 		if err.Error() != stoppedInMiddle {
> ```

nit: change to `if errors.Is(err, stoppedInMiddleError)`

matching the error message isn't reliable. see also https://pkg.go.dev/errors#Is
___
*[testserver/testserver.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBd2Zr-TFNkGHsz6BV:-MjBd2Zr-TFNkGHsz6BW:b-4gcg4r) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver.go#L149)):*
> ```Go
> 	ts, err := NewTestServer(opts...)
> 	if err != nil {
> 		if err.Error() != stoppedInMiddle {
> ```

nit: change to `if errors.Is(err, stoppedInMiddleError)`

matching the error message isn't reliable. see also https://pkg.go.dev/errors#Is
___
*[testserver/testserver.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBcdLB-iYkm00dFvsk:-MjBcdLB-iYkm00dFvsl:bq0zbn8) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver.go#L235)):*
> ```Go
> }
> 
> const stoppedInMiddle = "download stopped in middle"
> ```

nit: this should be:
```
var stoppedInMiddleError error = errors.New("download stopped in middle")`
```
___
*[testserver/testserver.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBdTvnA0biL7ZQdRLn:-MjBdTvnA0biL7ZQdRLo:b-4gcg4r) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver.go#L269)):*
> ```Go
> 		cockroachBinary, err = downloadLatestBinary(&serverArgs.testConfig)
> 		if err != nil {
> 			if err.Error() == stoppedInMiddle {
> ```

nit: change to `if errors.Is(err, stoppedInMiddleError)`

matching the error message isn't reliable. see also https://pkg.go.dev/errors#Is
___
*[testserver/testserver_test.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBeH_8AM0zDnp38gKg:-MjBeH_8AM0zDnp38gKh:b-j6rd9r) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver_test.go#L220)):*
> ```Go
> // two goroutines, the second goroutine waits for the first goroutine to
> // finish downloading the CRDB binary into a local file.
> func testFlockWithDownloadPassing(
> ```

nice test!
___
*[testserver/testserver_test.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBeBBz5h7Fzpvtg6C3:-MjBeBBz5h7Fzpvtg6C4:b-yoqrye) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver_test.go#L271)):*
> ```Go
> 	// First NewDBForTest process to download the CRDB binary to the local file,
> 	// but killed in the middle.
> 	testserver.NewDBForTest(t, testserver.StopDownloadInMiddleOpt())
> ```

is there a way that the test can verify that this first download actually failed. (or at least verify that the DB didnt start up)


<!-- Sent from Reviewable.io -->

2021-09-09 23:48 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[testserver/binaries.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBaP3N7u_qh2BItVdu:-MjBtYaaCyuC2R6fGcr9:b-m16fax) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L56)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think it would be safest to add
```
defer func() { _ = localFileLock.Unlock() }()
```
</blockquote></details>

Nice catch, thanks!
___
*[testserver/binaries.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBajpaE4tTOfnXoczd:-MjBte4uCPiFzWRf9DNh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L73)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think `localFileLock.Unlock()` would be a bit more readable
</blockquote></details>

Done.
___
*[testserver/binaries.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBapiN3is_bLOmZjVY:-MjBuONn1rSyFgTD_rXI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L84)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: add a comment to the function now that it's public
</blockquote></details>

Done.
___
*[testserver/binaries.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBbH8F4mvyN5aQnVuB:-MjBuQ1z5-CcNBt8KqRH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L164)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: instead of `canBeLocked`, the name `locked` is more understandable
</blockquote></details>

Done.
___
*[testserver/binaries.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBbftK6eIENP-qTpIT:-MjBuTIIBniyCBDTBvit:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L165)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the error handling is more readable like this:

```
if err != nil {
  return "", err
}
if locked {
  // If local file can be locked ...
  // ... rest of the code
}
</blockquote></details>

Done.
___
*[testserver/binaries.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBc17G0XCriq-PThbQ:-MjBuVGr425rAX28-bUt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L169)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: change to "previous download failed in the middle, deleting and re-downloading"
</blockquote></details>

Done.
___
*[testserver/binaries.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBcF3b8QqDtC6SvNu2:-MjBuYCH0NLriqJV_7ql:b5u0s93) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L171)):*
> Done.
Done.
___
*[testserver/binaries.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBdFpA3xRbZVynnHOw:-MjBuZQx6XjsMko9_1lc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/binaries.go#L186)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: change to `if errors.Is(err, stoppedInMiddleError)`

matching the error message isn't reliable. see also https://pkg.go.dev/errors#Is

</blockquote></details>

Done.
___
*[testserver/testserver.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBd2Zr-TFNkGHsz6BV:-MjBub1fDFB6eEuTbF56:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver.go#L149)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: change to `if errors.Is(err, stoppedInMiddleError)`

matching the error message isn't reliable. see also https://pkg.go.dev/errors#Is
</blockquote></details>

Done.
___
*[testserver/testserver.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBcdLB-iYkm00dFvsk:-MjBucnI-AnQOsf6rGDD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver.go#L235)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this should be:
```
var stoppedInMiddleError error = errors.New("download stopped in middle")`
```
</blockquote></details>

Done.
___
*[testserver/testserver.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBdTvnA0biL7ZQdRLn:-MjBudRx9tTh44WIJHmu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver.go#L269)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: change to `if errors.Is(err, stoppedInMiddleError)`

matching the error message isn't reliable. see also https://pkg.go.dev/errors#Is
</blockquote></details>

Done.
___
*[testserver/testserver_test.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjBeBBz5h7Fzpvtg6C3:-MjBufxW0WGEMcKlkVay:bvcjhhn) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/a625026cbb15edb20aedc5b0081561d9310f7bee/testserver/testserver_test.go#L271)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there a way that the test can verify that this first download actually failed. (or at least verify that the DB didnt start up)
</blockquote></details>

Added [this part](https://github.com/cockroachdb/cockroach-go/pull/112/files#diff-1f98793725685c02c97226566316ce6041e8222c01dc6e1d4c3a625dd31b9962R154-R157) to ensure that the ts is truly stopped. It's a bit hard to verify if the download is actually failed, since `NewDBForTest()` doesn't return any info of the testserver.


<!-- Sent from Reviewable.io -->

2021-09-10 14:38 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[testserver/binaries.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjF8Cp02REadCEd0dom:-MjF8Cp02REadCEd0don:b2emlsb) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/851618e54330ce50285dfe45d0c4340ee2f8bcba/testserver/binaries.go#L56)):*
> ```Go
> 	localFileLock := flock.New(filePath)
> 
> 	defer func() { _ = localFileLock.Unlock() }()
> ```

nit: this defer should be moved so it's after the error check for `TryLock` (below the next if-statement)
___
*[testserver/binaries.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjF6T0G8SQE7q7Dw6if:-MjF6T0G8SQE7q7Dw6ig:bp8og4a) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/851618e54330ce50285dfe45d0c4340ee2f8bcba/testserver/binaries.go#L174)):*
> ```Go
> 		if err != nil {
> 			return "", err
> 		} else {
> ```

nit: we don't need the `else` since the previous `if` statement short-circuits

the reason i suggest this is because stylistically, it's more readable if the main logic of the function is indented as little as possible
___
*[testserver/testserver.go, line 152 at r4](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjF6z2D8rIliDkPOoBh:-MjF6z2D8rIliDkPOoBi:bpppl0b) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/851618e54330ce50285dfe45d0c4340ee2f8bcba/testserver/testserver.go#L152)):*
> ```Go
> 			t.Fatal(err)
> 		} else {
> 			// If the testserver is intentionally killed in the middle,
> ```

nit: i think it would be more readable if the conditions were inverted, and we avoid the unneeded `else`:

```
if errors.Is(err, errStoppedInMiddle) {
  // If the testserver is intentionally killed ...
  return nil, func() { /* ... */ }
}
t.Fatal(err)
```


<!-- Sent from Reviewable.io -->

2021-09-10 15:25 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[testserver/binaries.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjF8Cp02REadCEd0dom:-MjFHvCx5pQ5gbbjgh2n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/851618e54330ce50285dfe45d0c4340ee2f8bcba/testserver/binaries.go#L56)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this defer should be moved so it's after the error check for `TryLock` (below the next if-statement)
</blockquote></details>

Done.
___
*[testserver/binaries.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjF6T0G8SQE7q7Dw6if:-MjFHyLH1vx5rETHXaaB:bmnccf0) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/851618e54330ce50285dfe45d0c4340ee2f8bcba/testserver/binaries.go#L174)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: we don't need the `else` since the previous `if` statement short-circuits

the reason i suggest this is because stylistically, it's more readable if the main logic of the function is indented as little as possible
</blockquote></details>

That makes lots of sense, thanks! Done.
___
*[testserver/testserver.go, line 152 at r4](https://reviewable.io/reviews/cockroachdb/cockroach-go/112#-MjF6z2D8rIliDkPOoBh:-MjFICDpEjfMlQWoJMXr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/851618e54330ce50285dfe45d0c4340ee2f8bcba/testserver/testserver.go#L152)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think it would be more readable if the conditions were inverted, and we avoid the unneeded `else`:

```
if errors.Is(err, errStoppedInMiddle) {
  // If the testserver is intentionally killed ...
  return nil, func() { /* ... */ }
}
t.Fatal(err)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-10 15:32 UTC, rafiss approved these changes
lgtm! nice work

2021-09-10 15:58 UTC, merged