Define CockroachBinaryPath option for testserver.
cockroachdb/cockroach-go pull request #134
Opened 2022-05-08 06:00 UTC by gonzojive

CockroachBinaryPath is a TestServer option that can be passed to NewTestServer
to specify the path of the cockroach binary. This can be used to avoid
downloading cockroach if running tests in an environment with no internet
connection, for instance.

2022-05-08 06:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/134)
<!-- Reviewable:end -->

2022-05-17 21:56 UTC, rafiss requested changes
thanks for your contribution! could you add a test for this?

2022-05-19 03:41 UTC, gonzojive commented
> thanks for your contribution! could you add a test for this?

I added a basic test.

2022-05-19 03:55 UTC, rafiss requested changes
thank you! please rebase your changes on top of `origin/master`, and squash your commits into one.

2022-05-19 04:52 UTC, gonzojive commented
Done.

2022-05-19 04:58 UTC, rafiss approved these changes
thanks!

2022-05-19 04:58 UTC, merged