set cmd.Dir to stop directory pollution
cockroachdb/cockroach-go pull request #135
Opened 2022-05-14 01:18 UTC by chrisseto

Previously, invocations of TestServer would results in various _dump
    directories being created by the cockroachdb process. While these
    directories were empty, it was bothersome to see them created and
    show up in file exporers. This commit sets cmd.Dir to a temporary
    directory to avoid polluting the project directory of consumers.

2022-05-14 01:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/135)
<!-- Reviewable:end -->

2022-05-16 03:52 UTC, rafiss commented
I need to figure out why CI is broken... Trying in https://github.com/cockroachdb/cockroach-go/pull/132

2022-05-18 15:46 UTC, rafiss requested changes
nit: could you rebase on master instead of doing a merge?

2022-05-18 17:05 UTC, rafiss approved these changes

2022-05-18 17:06 UTC, rafiss approved these changes

2022-05-18 17:39 UTC, chrisseto commented
TFTR!

2022-05-18 17:39 UTC, merged